apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-deployment
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.app.replicasCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: {{ .Values.app.container.image }}:{{ .Values.app.container.version }}
          ports:
            - containerPort: {{ .Values.app.container.port }}
          env:
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.app.env.SPRING_DATASOURCE_URL }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.app.env.SPRING_DATASOURCE_USERNAME }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.app.env.SPRING_DATASOURCE_PASSWORD }}
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
              value: {{ .Values.app.env.SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-service
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
  - protocol: TCP
    port: {{ .Values.app.service.port }}
    targetPort: {{ .Values.app.service.targetPort }}